github: [abeeraamir98]  # Your GitHub Sponsors username
patreon: abeer-amir  # Replace if you have a Patreon account
open_collective: abeer-amir  # Replace if you have Open Collective
ko_fi: abeeramir00  # Your Ko-fi username
tidelift:  # Leave blank if not using Tidelift
community_bridge:  # Leave blank if not using Community Bridge
liberapay:  # Leave blank if not using Liberapay
issuehunt:  # Leave blank if not using IssueHunt
lfx_crowdfunding:  # Leave blank if not using LFX Crowdfunding
polar:  # Leave blank if not using Polar
buy_me_a_coffee: abeeramir00  # Your Buy Me a Coffee username (if you use it)
thanks_dev:  # Leave blank if not using thanks.dev
custom: [
    'https://wa.me/923006190087',  # WhatsApp direct message link
    'https://abeeraamir98.github.io/Abeer-Amir/'  # Your website link
]
